### ISSUE TITLE
Query Parsing Exception

### ISSUE THREAD

**Issue by jadamconnor** [firebase/flashlight#130]
I get the following error when the value of q is a string with an odd number of quotes:

    "[query_parsing_exception] Failed to parse query [nded, \"Look, alt] ... "

Is this a Flashlight related issue, or is it something from Bonsai/ES? The query seems to expect the quote to be closed.

My query is comprised of highlighted text, which will invariably contain quotes. Currently, I'm working around the issue by not allowing queries with lone quotes, but I'd like to know if there is a way to allow such queries.

**Comment by katowulf** [comment]
Unsure. But what is certain is that Flashlight just directly passes on what you put into `q` without any fuss or modification.

What happens if you try exactly the same `q` syntax directly against ES? Do you get the same error? If it fails against ES, then I'd say it's just invalid syntax and you need some escaping on the quotes. If it works against ES, then it could be a problem with the JSON parsing or the elasticsearch.js npm library.

If it's the latter (i.e. it works against ES) exactly as you write it to the database, then could you create a minimal repro with versions info, sample data, and steps to repro?

**Comment by jadamconnor** [comment]
A little more research yielded [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters). Essentially, double quotes are in the list of reserved characters.
