### ISSUE TITLE
invalid string length

### ISSUE THREAD

**Issue by pdemilly** [firebase/flashlight#32]
I have tried with both flashlight and flue (a fork I found on github with a port to firebase 2.2) and I am getting the same error.
 
Any help appreciated

/home/search/flue/node_modules/firebase/lib/firebase-node.js:170
cket_failure")};function fh(a,b){a.frames.push(b);if(a.frames.length==a.Ze){va
                                                                    ^
RangeError: Invalid string length
    at Array.join (native)
    at fh (/home/search/flue/node_modules/firebase/lib/firebase-node.js:170:431)
    at va.onmessage (/home/search/flue/node_modules/firebase/lib/firebase-node.js:169:143)
    at EventTarget.dispatchEvent (/home/search/flue/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at instance._receiveMessage (/home/search/flue/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at null.<anonymous> (/home/search/flue/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emit (events.js:129:20)
    at null.<anonymous> (/home/search/flue/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/home/search/flue/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/home/search/flue/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)

**Comment by katowulf** [comment]
Considering that the error is entirely in the faye websocket lib, I'm going to take a quick guess that this isn't related to flashlight, but instead is an issue with faye/firebase versions.

**Comment by katowulf** [comment]
Please resubmit with a minimal repro and steps to run if you feel this is related to Flashlight.

**Comment by ekaram** [comment]
Kato,

I have experienced this issue as well, and have traced the root cause to an OOM error within node.

I have large collections that I wish to replicate in flashlight, but node crashes and I get the same error after the .on('child_added") code executes against a very large collection (~500mb). 

From your documentation: 

>  It won't trigger until the entire contents has been synchronized.

I have increased node memory max size, and have not been able to resolve this issue.  A simple 'fix' on my side just for testing this with one of my large collections was to add a .limitToFirst(xx)  on the ref that gets synced.  (PathMonitor:20,21,22) With the limit in place, my index replicates properly. 

Do you have any recommendations for this from an architecture standpoint?  I anticipate my existing collections that are currently functioning fine in production will grow soon, and this library will not be able to support them syncing a given path at that point in time.  

Interested in hearing your thoughts on data segmentation or alternate approaches for dealing with a growing data set.  There isn't *much* nested data at this path, there are just many, many records. 

Thanks,
Erin

**Comment by katowulf** [comment]
You'll certainly want to adapt what you query against. Maybe create a separate queue for your indexed entries and delete those after processing, use a timestamp based query (only look at items posted in the last 24/36/72 hours), et al. 

At some point, we might want to address this in Flashlight itself, by adding a timestamp parameter or similar, but to be honest, Firebase really isn't going to scale to queries against paths with millions or billions of records in them. The data needs to be segmented more effectively.

For example, a common approach here is to have something like the following:

```
/messages/latest
/messages/2016/11
/messages/2016/10
/messages/2016/09
/messages/2016/...
```

Now on the client, you're always grabbing latest (which probably about a month of overlap before the previous month's items are archived out to their own path). When users scroll back far enough in history, you probably start looking at the archived data.

In this manner, the work on the server is reduced significantly, since it doesn't have to load and parse millions or billions of records into memory in order to construct the indices and filter by queries.

Note that for big data paths that can't be indexed and archived by date (say if your system has 10 million users and you want those searchable) you probably want to maintain some sort of `modified_users` queue and index/delete the items there, so you aren't processing the same millions over and over.

**Comment by ekaram** [comment]
Thanks - this helps.  I think we'll look to incorporate both approaches with different data sets.
