### ISSUE TITLE
Error: ref.child(...).push(...).key is not a function

### ISSUE THREAD

**Issue by Nicolazinho** [firebase/flashlight#55]
In example.js line 26 is the following:
`var key = ref.child('request').push({ index: index, type: type, query: query }).key();`
which gives me the error in the subject line.

Just if I change `.key()` to  `.name()` I get the correct push ID in return. Is that a bug?

I am using Firebase version 2.2.9.

**Comment by drtriumph** [comment]
I can't reproduce this given the simple code:
```js
var Firebase = require('firebase');

var ref = new Firebase('https://your-db.firebaseio.com/');

console.log(ref.push().key());
console.log(ref.push({foo: 'bar'}).key());
```
and package.json:
```json
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "firebase": "2.2.9"
  }
}
```
Can you send an [mvce](http://stackoverflow.com/help/mcve) once you have it repeating. The `name()` method was deprecated in Firebase v2.0.0 - is it possible you're using an old version of the client?

**Comment by Nicolazinho** [comment]
Hi Chris,

Thanks for your reply. I used the code from example.js and stripped down as much as I could. I am left with this [codepen](http://codepen.io/anon/pen/yeGPeV?editors=1010) and as you can see in the console I am still getting the error. I am importing Firebase 2.4.0.

Any ideas?

**Comment by puf** [comment]
> ref.child('request').push({foo: 'bar'}).val()
> Uncaught TypeError: ref.child(...).push(...).val is not a function

Firebase.push() returns a Firebase object, which doesn't have a val()
method. If I change that to:

> var key = ref.child('request').push({foo: 'bar'}).key();
That error disappears, although of course this warning remains:

>FIREBASE WARNING: Firebase error. Please ensure that you spelled the name
of your Firebase correctly (https://my-db.firebaseio.com)

**Comment by katowulf** [comment]
Nicalazinho,

Hi there! First of all, your codepen doesn't match your original issue or verify it in any way. The original error was about name/key, and the codepen is complaining about .val().

So let's address the codepen first:  There is no .val() on a Firebase ref ([API here](https://www.firebase.com/docs/web/api/) so this isn't going to work.

Stepping back to the original example.js (assuming you mean [this one](https://github.com/firebase/flashlight/tree/master/example), then the problem is that that example uses this CDN version in index.html:

```<script type="text/javascript" src="https://cdn.firebase.com/v0/firebase.js"></script>```

Now, you can't simply change that out for a newer major release (i.e. 0.x to 2.x) without any incompatibility issues. However, this doesn't explain your .name()/.key() issue. I don't see any .name() references in examples.js other than the commented out line:

```//      console.log('result', snap.name(), snap.val());```

Obviously, if you want to upgrade the Firebase version from 0 to 2, you'll need to change out .name() there for .key().

To be any more helpful, you'll need to create a [real mcve](http://stackoverflow.com/help/mcve) that actually provides a **minimal, complete, verifiable, repro** of your issue.

**Comment by Nicolazinho** [comment]
Hi Firebase team,

Thank you for your quick reply and support.

First off: My apologies. Yes, I created the codepen with .val() instead of the .key() I was referring to and that I had the problem with. Sorry for the confusion. 

Kato's replied helped me figure it out: The [index.html](https://github.com/firebase/flashlight/blob/master/example/index.html) referred in line 70 to an old Firebase version `<script type="text/javascript" src="https://cdn.firebase.com/v0/firebase.js"></script>`. But with that .key() (in [example.js](https://github.com/firebase/flashlight/blob/master/example/example.js) line 28) does not work. So I replaced the Firebase version in index.html with a newer version (after v2.0.0 per Chris' comment) and then it worked.

I would suggest updating that in index.html as well or at least adding a comment to upgrade to a version >2.0.0

Thanks again for your help!

**Comment by skhabeeb42** [comment]
Hi,

I am using firebase 3.0. when i am trying to get the key using key() i am getting an error uncaught exception key() is not a function.

my code is as follows

firebase.database().ref('stories/story').on('value', function(snap)
{
   var strykey = snap.key();
});

and my data in firebase is as follows

stories
      story
            -KKH8AevJUJIrjuz07pTaddclose
                 status: "0"
                 storyname: "story1"

**Comment by VinuOye** [comment]
Hi Skhabeeb42,

Just replace the **.key()** into **.key**. in firebase 3.x **key()** function is replaced with **key**

firebase.database().ref('stories/story').on('value', function(snap)
{
var strykey = snap.key;
});

Hope this works well.

Thanks,
Vinodh

**Comment by skhabeeb42** [comment]
Hi Vinodh,

Thank You. It worked.
