### ISSUE TITLE
Memory usage & timeouts

### ISSUE THREAD

**Issue by laurensnl** [firebase/flashlight#67]
Hey guys,

I've got a database that I get indexed in Elasticsearch using flashlight. All worked fine for a while, but the database grew quite a lot lately and when I re-indexed the whole database today, I got a lot of errors:

Error: Request Timeout after 30000ms

Our database has about 50.000 records that should be indexed, but many are now missing. How to prevent this?

Also, I noticed that this script uses at least as much memory as the size of the database. Is there a way to reduce this?

**Comment by rohit-raj** [comment]
Hi,

You can add the requestTimeout in app.js while initialising the elastic search client.

```
var esc = new ElasticSearch.Client({
  hosts: [
    {
      host: conf.ES_HOST,
      port: conf.ES_PORT,
      auth: (conf.ES_USER && conf.ES_PASS) ? conf.ES_USER + ':' + conf.ES_PASS : null
    }
  ],
  requestTimeout: 1200000   //this is 20 minutes
});
```

Please let me know for more info

**Comment by laurensnl** [comment]
Thanks @rohit-raj! Much appreciated! I did this but I put the requestTimeout in the hosts object so that didn't work. 

Is it to be expected that Flashlight uses as much memory as the size of the database?

**Comment by rohit-raj** [comment]
Hi,
Thanks for the appreciation.
No, I dont think that flashlight will use memory as the size of db, just because it is only an app running that takes each firebase record/data and index it to the ES. Hence the indexer is not saving the data in itself rather writing it to the ES which will not increase the size of your app.

The indexer do create socket(s) to communicate with ES, but when I saw the process stats it was not that high. I do have around half a million record but that does not burn out the whole memory.

I hope this clears your doubt.

**Comment by laurensnl** [comment]
That's what I thought. Weird thing is that it does use about 1GB of memory (as indicated by PM2). At least I know now that it isn't supposed to use as much memory so I'll start digging to find the cause!

Thanks again!

**Comment by katowulf** [comment]
So the Firebase SDK loads the data into memory in order to trigger child_added events, so it will in fact load all the records at the path. A simple way to make this scale to that level would be to timestamp your records and add a query to your ES worker to only fetch records newer than some reasonably recent timeframe.

Of course, that will only scale you so far as well. Eventually you'll run out of capacity on the server if your node structure becomes too bulky (e.g. millions of records).  So the best answer here will be to archive old data in some manner (split records by month/week/year et al) and to only have ES monitor data that is actually in circulation and changing for updates.

**Comment by laurensnl** [comment]
Thanks for your response @katowulf! So it ís to be expected that the memory usage is as large as the database itself. For most data, it is important that it's all in ES, so the timestamping solution wouldn't work here. I was hoping that Firebase would scale better. Guess it's not really meant for large apps. A kind of native ES indexing solution (without the need to do this ourselves) or more complex queries built in Firebase would be awesome!

Thanks again for your input though! Much appreciated!

**Comment by katowulf** [comment]
In memory usage is expected to be as large as the amount of data queried. Not as large as the database, unless you're trying to index the entire thing with one worker. Flashlight isn't an enterprise production app, it's an OSS proof of concept. 

Modifying it to serve your particular use case would likely just involve modifying how the data is queried and how you notify it to reindex after changes. Creating an app for a specific use case is probably trivial. Trying to create an enterprise app to meet everyone's needs will not be.

☼, Kato

**Comment by laurensnl** [comment]
Thanks for the clarification @katowulf! Will try multiple workers in combination with the timestamp solution for old data that doesn't need to be updated anymore. 

Have a great day!

Laurens
