### ISSUE TITLE
Nested Query?

### ISSUE THREAD

**Issue by stevejcox** [firebase/flashlight#84]
Hi Guys,

I have a document that looks like: posts -> userKey -> postKey -> description

Do you have any suggestions on how I can query on the description without knowing the keys? I've taken a look at has_child query, but this requires mapping the _parent (which i don't know).

Thanks,
Steve

**Comment by katowulf** [comment]
Is this a question about how querying works in ElasticSearch, a question about how querying works in Firebase, or something I've missed related to Flashlight?

**Comment by stevejcox** [comment]
Well, I guess both querying for elasticsearch and for flashlight. Is this just a case of finding the right query for elasticsearch or to do this sort of query do I need to also modify flashlight? 

I've implemented several outstanding PR's to get flashlight to send the query's to elasticsearch, so I am unsure whether flashlight should handle this type of request or whether it needs modifying.

I tried using a request like below, but there's no relationship between child and parent within elasticsearch for my document: 
```
"query": {
                 "has_child": {
                     "type": "video",
                     "query": {
                         "query_string": {
                            "query": "s*",
                         }
                     }
                 }
             }
```

Any suggestions would be hugely helpful.

**Comment by katowulf** [comment]
Happy to help. What are the constraints here? Why are posts indexed by uid? Is this structure flexible or a hard requirement? Are these blogs of some sort, owned by exactly one user? If not, this probably isn't the best structure. Can you provide some actual sample data?

**Comment by stevejcox** [comment]
Thank you!

This is a social app (think instagram like). I'm storing each post in various locations including the user's followers feeds and their own feed. In this example it's the user's own posts. So i am using their userKey (same as uuid) followed by the postKey. The structure is flexible if necessary. 

The search functionality should look at the post's description and return the post if it matches the query. I have everything working fine for other searches, but this one has the additional level which is tripping me up.

example of the data below:

```
{
  "-KOGvlay1EUAgWUDpCKg" : {
    "-KSCdxiRcScWKO61wQegf" : {
      "authorKey" : "-KOGvlay1EUAgWUDpCKg",
      "description" : "#Football!",
      "firstname" : "Scott",
      "height" : 720,
      "lastname" : "MacDonald",
      "url" : "",
      "username" : "scottamcdonald",
      "width" : 1280
    }
  },
  "zLgoDoxVCMaQYDyCU1CrLM6dTQe2" : {
    "-KScTp_S6gFfyHY4vai3" : {
      "authorKey" : "zLgoDoxVCMaQYDyCU1CrLM6dTQe2",
      "description" : "Sound of the #waves #timelapse #photography",
      "firstname" : "steve",
      "height" : 720,
      "lastname" : "cox",
      "url" : "",
      "username" : "stevejcox",
      "width" : 1280
    },
    "-KScURcTwEfLgpdc0LOA" : {
      "authorKey" : "zLgoDoxVCMaQYDyCU1CrLM6dTQe2",
      "description" : "Test",
      "firstname" : "steve",
      "height" : 720,
      "lastname" : "cox",
      "url" : "",
      "username" : "stevejcox",
      "width" : 1280
    }
  }
}

```

**Comment by katowulf** [comment]
And how are searches conducted? What constraints exist on those?

**Comment by stevejcox** [comment]
Searches are across all posts. So with that being said an option is to have a document with all posts, which would remove 1 level.

Thanks for the reminder about security, will take it into account.

**Comment by katowulf** [comment]
Yep, so now that I sort of understand (not completely) what you're aiming for here, I think the options are probably as follows:

**1) Create a queue to consume items you want indexed**

Dual-write messages to the users' feeds and to something like [firebase-queue](https://github.com/firebase/firebase-queue) (or just any temporary path). Consume those messages and index them in ES using a pattern similar to Flashlight, then delete them after successful indexing is completed.

This is highly scalable and robust (if your indexing service crashes or is restarted, there's no losses; it minimizes the amount of data that has to be monitored by the service since old records are deleted and only new records need to be downloaded).

**2) Hack the Flashlight code to handle nested records**

In app.js, instead of just indexing records using `conf.paths`, monitor the `/posts` path for child_added events (i.e. new feeds to watch) and [call PathMonitor.process()](https://github.com/firebase/flashlight/blob/master/app.js#L27) on each, rather than once on the `/posts` path.

Some thought should be given to how this will scale. It would technically download all items under `/posts` at least once per service restart. Note that you could improve this performance by doing a REST GET request with `shallow=true` to just fetch the keys, or even get a list of the user ids from another path (an index you create for example) rather than obtaining it by downloading `/posts`.

**3) Dual-write messages to another path**

This is the solution you suggested and is similar to 1) above with a couple important caveats:  It's simpler; it's less scalable since we aren't deleting records after they are processed, which means every post will be downloaded at least once per service restart.

Note that this can be countered by not monitoring the whole path, but instead by adding a timestamp to each record and doing something like `ref.orderByChild('timestamp').startAt( Date.now() - 3600 /* items added in the last hour only */ )` [here](https://github.com/firebase/flashlight/blob/master/lib/PathMonitor.js#L119).

That modification would provide decent scale, but still not as scalable or robust as deleting processed records as in 1) above.

**Comment by stevejcox** [comment]
This is a hugely helpful response, thank you so much for the time to write it.

I'll explore these options a bit, but this is a great kicking off point to get cracking. Thanks again man.
