### ISSUE TITLE
Passing Escaped JSON Search String

### ISSUE THREAD

**Issue by ekaram** [firebase/flashlight#91]
Kato & team,

I'm excited to see you have recently been working to upgrade this library!  Huge thanks for this.  

I recently pulled your latest code.  My code using previous version was serializing my elastic search string, as it contains '.' values which cannot translate into valid json for posting to firebase at /search/request.

I noticed the latest code no longer calls a JSON.parse() on the query before passing to elastic.  I'm now getting this error: 

  error: 
   { [Error: [query_parsing_exception] Failed to parse query [{"bool":{"should":[{"term":{"organizations.-Jj61H3Hx45g8IUbihXw":true}},{"term":{"clients.-JyZ-yV6aHJU35QhJHBU":true}}],"minimum_sh
ould_match":1,"must":[{"query_string":{"fields":["data.firstName","data.lastName"],"query":"**"}}]}}]

Can you please advise?

**Comment by katowulf** [comment]
You can [pass a `parser` function](https://github.com/firebase/flashlight/blob/master/lib/PathMonitor.js#L13) as part of any of the paths in [conf.paths](https://github.com/firebase/flashlight/blob/master/config.js#L62) and call JSON.parse() yourself.

```
function parserMethod(data) {
    return {
         foo: data.foo + 1,
         bar: JSON.parse(data.bar)
    }
}


exports.paths = [
   {
      path : "users",
      index: "firebase",
      type : "user",
      parser: parserMethod
   }
];
```

**Comment by ekaram** [comment]
It's my understanding the parser method is for intercepting data as it's being synced.  

I was referring to my actual query used to search.  I post my query at /search/request.  I use an escaped string since my query contains '.' and I can't use json directly.

The below commit contains a change that removed code that parsed my serialized search string. 

This parse went away: (line 21) 
var queryObj = this._isJson(dat.query) ? JSON.parse(dat.query) : dat.query;

https://github.com/firebase/flashlight/commit/46fb4bb6b9bd9940f2cbb04993083be0c0d267fd#diff-b4e918f2d7fecadebef380f5ab9f31cf

**Comment by ekaram** [comment]
this adjustment worked for me: 

```
if (typeof dat.query === 'string') {
        if (this._isJson(dat.query)) {
          searchProps.body = {
            query: JSON.parse(dat.query)
          };
        } else {
          searchProps.q = dat.query;
        }
      } else {
        searchProps.body = {
          query: searchProps.query
        };
      }
```

**Comment by katowulf** [comment]
Ah, for queries, there's no reason to pass a string representing a query object. You can directly pass anything that would be accepted as the `body` of an ES query in that field (it can be a string or an object). You probably need the latest updates to make that work.

**Comment by ekaram** [comment]
```
{"bool":
  {"should":
      [{"term":
        {"organizations.-K0bUp1j_kasKXWHPoc9":true}},
        {"term":{"clients.-K0T-TL1wmD78tK_HzQo":true}}],
    "minimum_should_match":1,
    "must":
       [{"query_string":{"fields": ["data.firstName","data.lastName"],"query":"j*"}}]}}
```

I cannot post the above ES query to firebase /search/request as JSON, as firebase does not accept the invalid '.' characters in the key "clients.-K0T-TL1wmD78tK_HzQo" : true 
 
Am I missing something? Do you mean latest 'ES' query updates, and not flashlight updates?

**Comment by katowulf** [comment]
Hm, very interesting. Any other meta characters that can be used in keys that would be an issue? For example using `/` or `?`? Let's see if we can define the scope here and come up with an effective solution. I don't want to just blindly parse anything that can be parsed (i.e. searching for `[1]` should not automatically get parsed into an array containing an integer). But I do understand the end goal here, now.

I've been a bit annoyed by the disparity between the client and server sides for a bit, anyway. Initially, it seemed simpler to just have `query` on the clients and take care of parsing what that means to ES on the server, but that's probably too naïve. 

Maybe it's time to just go ahead and change `query` on the client to optionally providing one of `body` or `q` and then, in the case that `body` is a string, always assuming it's a valid JSON string (since `q` can be passed for rudimentary string searches).

Do I have all my ducks in a row here? Anything missing?

**Comment by ekaram** [comment]
That sounds like a good adjustment to me.  Thanks for being so responsive to this.
