### ISSUE TITLE
serviceAccount property is not supported anymore without firebase-admin sdk

### ISSUE THREAD

**Issue by mkim871** [firebase/flashlight#97]
It returns an error like below.

`The 'serviceAccount' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started`

**Comment by katowulf** [comment]
It's still supported, it's just deprecated.

**Comment by glennposadas** [comment]
hi @katowulf , I'm posting my query in this thread since the crash might be connected to what TS has posted.

Can you help me checking out this error? I really need a help. Thanks!

![screen shot 2016-12-15 at 11 49 22 pm](https://cloud.githubusercontent.com/assets/12502679/21230865/45e98b00-c321-11e6-9ed2-4e054c5ed322.png)

**Comment by katowulf** [comment]
That's still just a warning. Deprecated does not mean broken. It's unlikely that's the cause of the crash. A full repro with more verbose logging and some due diligence, posted to your own issue, would be necessary to help here.

**Comment by glennposadas** [comment]
Thank you so much @katowulf . I made a quite long post (As issue) here: https://github.com/firebase/flashlight/issues/108

**Comment by katowulf** [comment]
Fixed by #105
