### ISSUE TITLE
How would this work with authed user data?

### ISSUE THREAD

**Issue by Jonovono** [firebase/flashlight#98]
Hi. I am new to firebase so maybe this is obvious.

But I have users auth into my app (simple chat message app). I want them to be able to search only messages they have sent/recieved.

My structure looks like:

```
users/
    <user_id>/
        chats/
            1/
                messages/
                     message_id/
                          text: "message text"
            2/
            .....
```

I want Elasticsearch to be able to search the "text" field on each message, but only for that authed user.

Any help would be great!

Thanks.

**Comment by katowulf** [comment]
Since the ES requests are funneled through your Flashlight service, this would be the ideal place to apply security to the ES search data. Some assembly is going to be required.

The simplest answer is probably to a) apply security rules to the path your client writes (see example.js) to make the request, which will allow you to verify the user is authenticated and not spoofing their uid and b) use the .filter option in config.example.js to filter data based on that user id.

Another option would be to store the data in ES segmented by uid or some other criterium (i.e. the type could become something like user:<uid here>.

☼, Kato

**Comment by hyperbrave** [comment]
@katowulf  are there any flashlight examples for exporting paths similar to the one @Jonovono posted?

```
  {
    path: "users/?/chats/?/messages/",
    index: "firebase",
    type: "messages",
    fields: ['text' ...],
    indexBy: "key"

users/
    <user_id>/
        chats/
            1/
                messages/
                     message_id/
                          text: "message text"
            2/
            .....
```

**Comment by katowulf** [comment]
Speaking broadly, you should [avoid that kind of nesting](https://firebase.google.com/docs/database/android/structure-data#avoid_nesting_data) whenever possible. Generally speaking, you should denormalize your user meta data, messages, and chat meta data. Pretty much every example in the docs and all our samples cover similar ground and best practices.

To directly answer the question, you could pull this off by [loading your paths from the database](https://github.com/firebase/flashlight#loading-paths-to-index-from-the-database-instead-of-config-file). When a new chat is added, put it into the `dynamic_paths` data so that it will be indexed. But flattening data a bit would, again, make this much simpler.

**Comment by hyperbrave** [comment]
@katowulf thanks for the reply, that's what I was anticipating
